services:
  my_web:
    build: .
    ports:
      - 8080:80
    volumes:
      - "./php:/var/www/html"
  my_db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=ciccio
    volumes:
      - "./mysql:/var/lib/mysql"
  my_phpMyAdmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
